services:
  postgres:
    image: postgres:16-alpine
    container_name: foundry-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: foundry
      POSTGRES_USER: foundry_user
      POSTGRES_PASSWORD: foundry_password
    ports:
      - "13001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U foundry_user -d foundry"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    container_name: foundry-mailhog
    restart: unless-stopped
    ports:
      - "13004:1025"  # SMTP server
      - "13005:8025"  # Web UI
    environment:
      MH_STORAGE: memory
      MH_SMTP_BIND_ADDR: 0.0.0.0:1025
      MH_API_BIND_ADDR: 0.0.0.0:8025
      MH_UI_BIND_ADDR: 0.0.0.0:8025

  redis:
    image: redis:7-alpine
    container_name: foundry-redis
    restart: unless-stopped
    ports:
      - "13007:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-foundry_redis_password}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "foundry_redis_password", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: foundry-redis-commander
    restart: unless-stopped
    ports:
      - "13008:8081"
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379:0:foundry_redis_password

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local