version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: foundry-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: foundry
      POSTGRES_USER: foundry_user
      POSTGRES_PASSWORD: foundry_password
    ports:
      - "13001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U foundry_user -d foundry"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    container_name: foundry-mailhog
    restart: unless-stopped
    ports:
      - "13004:1025"  # SMTP server
      - "13005:8025"  # Web UI
    environment:
      MH_STORAGE: memory
      MH_SMTP_BIND_ADDR: 0.0.0.0:1025
      MH_API_BIND_ADDR: 0.0.0.0:8025
      MH_UI_BIND_ADDR: 0.0.0.0:8025

volumes:
  postgres_data:
    driver: local